apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-build-context
  namespace: rancher-questions-gen
data:
  Dockerfile: |
    FROM golang:1.21-alpine AS builder
    WORKDIR /app
    COPY go.mod go.sum ./
    RUN go mod download
    COPY . .
    RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd
    FROM alpine:latest
    RUN apk --no-cache add ca-certificates
    WORKDIR /root/
    COPY --from=builder /app/main .
    EXPOSE 8080
    CMD ["./main"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-build
  namespace: rancher-questions-gen
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=dir:///workspace"
        - "--dockerfile=/workspace/Dockerfile"
        - "--destination=rancher-questions-backend:latest"
        - "--cache=true"
        volumeMounts:
        - name: build-context
          mountPath: /workspace
        - name: source-code
          mountPath: /workspace/backend
          subPath: backend
      volumes:
      - name: build-context
        configMap:
          name: backend-build-context
      - name: source-code
        hostPath:
          path: /Users/erquill/Documents/GitHub/rancher-questions-generator
      restartPolicy: Never