apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-questions-generator.fullname" . }}-backend
  labels:
    {{- include "rancher-questions-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rancher-questions-generator.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rancher-questions-generator.backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rancher-questions-generator.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
      - name: copy-source
        image: alpine/git:latest
        command: ["sh"]
        args: 
          - "-c"
          - |
            if [ ! -d "/app/.git" ]; then
              git clone https://github.com/wiredquill/rancher-questions-generator.git /tmp/repo
              cp -r /tmp/repo/backend/* /app/
            fi
        volumeMounts:
        - name: source-code
          mountPath: /app
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
      containers:
      - name: backend
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command: ["sh"]
        args: ["-c", "cd /app && export GOCACHE=/tmp/go-cache && export GOMODCACHE=/tmp/go-mod && go mod tidy && go build -o main cmd/main.go && ./main"]
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        env:
          {{- toYaml .Values.backend.env | nindent 10 }}
        volumeMounts:
        - name: source-code
          mountPath: /app
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: /data
        {{- end }}
      volumes:
      - name: source-code
        emptyDir: {}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "rancher-questions-generator.fullname" . }}-data
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}