{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rancher-questions-generator.fullname" . }}
  labels:
    {{- include "rancher-questions-generator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rancher-questions-generator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "rancher-questions-generator.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.backend.service.targetPort }}
    - protocol: TCP
      port: {{ .Values.frontend.service.targetPort }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
  - {}
  {{- end }}
{{- end }}