name: Test Action Debug

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Debug test
      run: |
        echo "✅ GitHub Actions is working!"
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"